### ISSUE TITLE
Wob on focussed screen.

### ISSUE THREAD

**Issue by jameswalmsley** [francma/wob#10]
Is it possible to make Wob appear on the output with the current focus.
I don't mind implementing this myself if someone has some pointers of where to start..

**Comment by francma** [comment]
Current implementation is kind of naive - Wob picks first output that Sway throws at it. It should behave as you described it - show bar only on focused output. Sadly I can't give you any useful pointers as I'm kind of beginner in this myself.

**Comment by francma** [comment]
Fixed in [wob 0.7](https://github.com/francma/wob/releases/tag/0.7)
