### ISSUE TITLE
unknown keys border and offset

### ISSUE THREAD

**Issue by primalmotion** [francma/wob#106]
I was moving my flags to the ini file

background_color = 000000EE
bar_color = FFFFFFEE
border_color = FFFFFFEE
anchor = bottom
margin = 80
offset = 0
border = 1
height = 25

but I get:

1668910292.566530 ERROR config.c:256: Unknown config key offset
1668910292.566560 ERROR config.c:256: Unknown config key border

**Comment by francma** [comment]
Fixed in https://github.com/francma/wob/releases/tag/0.14.1

Correct configuration keys are `border_offset` and `border_size`

**Comment by primalmotion** [comment]
Great! Thanks!
