### ISSUE TITLE
Feature request: allow margin for top/bottom and left/right

### ISSUE THREAD

**Issue by stvsu** [francma/wob#110]
Looking at `main.c` line 129, it looks like `zwlr_layer_surface_v1_set_margin` allows for setting top, bottom, left and right margin.

Would you consider adding a config param to allow for `margin_x = value` (to set left and right) and `margin_y = value` (to set top and bottom)?

Ideally I would like to be able to offset the bar with different values for the x and y axis, rather than moving them in unison.

**Comment by stvsu** [comment]
This could also be solved by allowing two values for `margin = x-axis y-axis` e.g. `margin = 5 3` would set a left/right margin of 5px and a top/bottom margin of 3px.

**Comment by francma** [comment]
Hello. I prefer the variant with: 

```
margin = top right bottom left
margin = top-bottom right-left
margin = all
```

just like with css margin. Feel free to create a pull request.
