### ISSUE TITLE
Sandbox make wob to crash instantly on aarch64

### ISSUE THREAD

**Issue by stacyharper** [francma/wob#131]
Looks like the seccomp calls are wrong under this arch (maybe others?)

`Bad system call`

**Comment by francma** [comment]
Please provide the output of

```
strace wob
```

And you can set `WOB_DISABLE_PLEDGE` to temporary disable seccomp.

**Comment by stacyharper** [comment]
https://paste.sr.ht/~stacyharper/9a155872c3940f15e5f108fdb1630e5a8828a700

Yap, I avoided the problem with this environment variable:

https://git.sr.ht/~mil/sxmo-utils/commit/55aac86762c904a666b465cd95507e22093a3792

**Comment by stacyharper** [comment]
This is not the wob_pledge() call itself that crash, we crash when calling  wl_display_roundtrip(app->wl_display) after the seccom has been setup

**Comment by francma** [comment]
Should be fixed in https://github.com/francma/wob/commit/cd854397bca5d2a06c312e7cd877c8ab334449fa

Can you try if it fixes the problem?

**Comment by stacyharper** [comment]
It does! Thanks

**Comment by stacyharper** [comment]
Could you flag a minor? Or I will have to backport it to my distro

**Comment by francma** [comment]
https://github.com/francma/wob/releases/tag/0.15.1
