### ISSUE TITLE
Create and maintain distribution packages

### ISSUE THREAD

**Issue by francma** [francma/wob#2]
There is only one for Arch Linux. It would be nice to have packages for other popular distributions like Gentoo, Void and others.

Links to current packages are located in [README](https://github.com/francma/wob#installation).

**Comment by StephenCoady** [comment]
Happy to package for Fedora.

**Comment by primeos** [comment]
I've packaged it for Nix(OS) but initially missed this ticket :o Thanks for writing this tool :)

Regarding the README: You could also include a badge from Repology if you want: https://repology.org/project/wob/badges ;)

And Repology should also help tracking which distributions provide a package.

**Comment by mejo-** [comment]
I'd like to package wob for Debian. Unfortunately I cannot build the package from your release tarball as it doesn't contain the wlr-protocols subdirectory. Would you mind to vendor wlr-protocols in the release tarball?

Besides, it would be super nice if you could sign the release tarballs and the git tags in order to cryptographically verify that the files have not been tampered with in the supply chain.

**Comment by francma** [comment]
Sorry, been busy lately :crying_cat_face: 

I'll look into this during holidays.

**Comment by mejo-** [comment]
No worries. I'll wait for your feedback and/or a new release with vendored wlr-protocols before continuing with the packaging effort.

**Comment by m-rey** [comment]
There is some work being done regarding the package for openSUSE: https://github.com/openSUSE/openSUSEway/issues/17

**Comment by m-rey** [comment]
There's now a package for openSUSE: https://build.opensuse.org/package/show/openSUSE:Factory/wob
It can simply be installed with `sudo zypper in wob`.

**Comment by freijon** [comment]
Here is a working ebuild for Gentoo if anyone is interested: [wob-0.10.ebuild](https://gist.github.com/freijon/fbd7ff186cf25838b289301226b93cd8)

**Comment by francma** [comment]
I think it's time to close this now. 

Thank you, everyone :slightly_smiling_face:
