### ISSUE TITLE
AUR install is broken

### ISSUE THREAD

**Issue by y0ast** [francma/wob#37]
AUR install fails with:

```
:: Importing keys with gpg......
gpg: keyserver receive failed: No data
==> Error: Problem importing keys
```

Fix from: https://aur.archlinux.org/packages/wob/
```
gpg --keyserver keys.openpgp.org --receive-keys 5C6DA024DDE27178073EA103F4B432D5D67990E3
```

Not sure what causes the gpg import to fail, but it does.

**Comment by eoli3n** [comment]
+1

**Comment by francma** [comment]
I think that is how it is supposed to work. You don't have the PGP key which is used to sign the source files so it fails.

https://wiki.archlinux.org/index.php/Makepkg#Signature_checking

**Comment by eoli3n** [comment]
I confirm that we can't import the gpg key, as he showed you
```
❯ LANG=C gpg --recv-keys F4B432D5D67990E3
gpg: keyserver receive failed: No data
```

**Comment by francma** [comment]
What keyservers are you using?

**Comment by eoli3n** [comment]
```
❯ grep '^keyserver' ~/.gnupg/gpg.conf
keyserver hkp://keys.gnupg.net
```

**Comment by francma** [comment]
I've sent key to keys.gnupg.net, it should be working now.

Thanks :slightly_smiling_face:

**Comment by y0ast** [comment]
Does not seem to be working just yet:
```
$ gpg --keyserver keys.gnupg.net --receive-keys 5C6DA024DDE27178073EA103F4B432D5D67990E3
gpg: keyserver receive failed: No data
```

This is the default in arch:
```
$ gpg -v --receive-keys 5C6DA024DDE27178073EA103F4B432D5D67990E3
gpg: data source: https://82.148.229.254:443
gpg: keyserver receive failed: No data
```

Many users will install your package using `yay` or equivalents, which automatically imports (after asking...) the pgp key for AUR packages.

**Comment by francma** [comment]
Hmm, this time I used their web upload form instead of `gpg --send-keys`. Seems to be working in clean docker image.

```

**Comment by eoli3n** [comment]
It worked for me, thx

**Comment by y0ast** [comment]
`yay` now installs `wob` and adds the key without complaining! :+1: 

Thanks @francma
