### ISSUE TITLE
styling with colors

### ISSUE THREAD

**Issue by eoli3n** [francma/wob#38]
Is there a way to style wob with colors, radius or else ?

**Comment by njoyard** [comment]
Radius is not possible, wob only draws rectangles.

Colors can be customized either on the command line (see `wob --help`) or when piping commands to it (eg `42 #aarrggbb #aarrggbb #aarrggbb`, colors being background, border and bar respectively).

Geometry can be customized on the command line, too (see `wob --help` as well).

**Comment by eoli3n** [comment]
Thanks, is there any way to add the radius feature ?

**Comment by progandy** [comment]
> Thanks, is there any way to add the radius feature ?

Yes, but you'd have to do some maths and calculate the pixels for the arc manually (e.g. Bresenham algorithm) since wob does not use any graphics library.

**Comment by eoli3n** [comment]
Any exemple to understand ?

**Comment by progandy** [comment]
> Any exemple to understand ?

Here is some information if you want to try to implement it: http://members.chello.at/~easyfilter/bresenham.html

**Comment by eoli3n** [comment]
I use wob 0.8.1 and i don't see anything related to colors configuration in ``wob --help``.

```
➜ wob --help                                                                                                                                                                                                                        17:36:01
wob: invalid option -- '-'
Usage: wob [options]

  -h        Show help message and quit.
  -v        Show the version number and quit.
  -t <ms>   Hide wob after <ms> milliseconds, defaults to 1000.
  -m <%>    Define the maximum percentage, defaults to 100. 
  -W <px>   Define display width in pixels, defaults to 400. 
  -H <px>   Define display height in pixels, defaults to 50. 
  -o <px>   Define border offset in pixels, defaults to 4. 
  -b <px>   Define border size in pixels, defaults to 4. 
  -p <px>   Define bar padding in pixels, defaults to 4. 
  -a <s>    Define anchor point; one of 'top', 'left', 'right', 'bottom', 'center' (default). 
            May be specified multiple times. 
  -M <px>   Define anchor margin in pixels, defaults to 0. 
  -O <name> Define output to show bar on or '*' for all. If ommited, focused output is chosen.
            May be specified multiple times.
```

No way to add colors in config file ? it will centralize config and would be easier to implement...

**Comment by eoli3n** [comment]
For the radius feature, a user friendly config would be great, i can't understand why you can't wrap maths in wob to calculate radius.

**Comment by francma** [comment]
> No way to add colors in config file ?

No.

> Thanks, is there any way to add the radius feature ?

Maybe. Not a priority in my eyes right now.

> I use wob 0.8.1 and i don't see anything related to colors configuration in wob --help.

It will be part of a next release.
