### ISSUE TITLE
Feature request: add rotation option

### ISSUE THREAD

**Issue by paper42** [francma/wob#44]
Something like `-r, --rotate=vertical` would be nice.

**Comment by PaperMountainStudio** [comment]
I was thinking about this and maybe something like rotate=90 (degrees) would be better if it is not too much harder to implement. Imagine someone wanted to create a bar which goes from up to down, this way wob wouldn't need another flag which reverses the direction of the bar.

**Comment by 0Karakurt0** [comment]
There is another way to do it, automatic one. It limits directions to only 2, but why would you need more anyway?
What I am talking about is to define direction based on geometry.
If Width > height then horisontal; else vertical. Something along these lines

**Comment by 0Karakurt0** [comment]
I tried to implement my idea, but could not get it to work somewhy

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
#97 works well and I've been using it for a week with no issues.
