### ISSUE TITLE
Feature request: Allow values over 100

### ISSUE THREAD

**Issue by m-rey** [francma/wob#54]
It would be nice if values over 100 would be accepted and just displayed as if it they were 100. That way, when using wob for volume with audio boost (which allows values over 100), no hacky workaround would be needed to dsplay it correctly.

**Comment by Axenntio** [comment]
You can simply get the minimum value between 100 and your volume output :
```bash
dc -e "[`pamixer --get-volume`]sM 100d `pamixer --get-volume`<Mp"
```
`100` is here to avoid getting over 100
`pamixer --get-volume` is the command that get the volume

**Comment by Brod8362** [comment]
I'm willing to implement this. Maybe add a flag to enable/disable it, allow a different color when the bar is over 100% (and maybe have it wrap around in that color?), etc.
