### ISSUE TITLE
Release archives are tar instead of gzip

### ISSUE THREAD

**Issue by freijon** [francma/wob#55]
I'm getting strange errors while trying to upgrade wob from 0.8 to 0.10 on my Gentoo machine. After some investigation with `file` it seems that the .tar.gz in the Release section of versions 0.10 and 0.9 are only TAR files, despite the extension .tar.gz. Version 0.8 was fine and is actually compressed with gzip.
Is it possible that you made a mistake while creating the archives?

**Comment by francma** [comment]
Yes, you are right. I've automated this in 22a866e04fefc094805309b1dde3e1e57dcc9d0e so I don't make this silly mistake again :slightly_smiling_face:
