### ISSUE TITLE
seg fault

### ISSUE THREAD

**Issue by rodneydup** [francma/wob#56]
In brief: Trying wob 0.10.0 on my system just results in a seg fault.

Dist: Debian 11
Kernel: 5.8 (amd64)
DE: Gnome 3.36.4 (wayland of course)

repro:
- build wob, everything fine
- open terminal
- type 'wob'
- press return
- type integer between 0-100
- press return
"Segmentation fault"

I'm not sure at this point what steps I could take to debug and give more information...

**Comment by francma** [comment]
GNOME doesn't support the layer-shell protocol. Wob should now exit instead of segfault ad26118881a071057f7b9ecaa13d384429a6e36a
