### ISSUE TITLE
Cannot set border background or bar color with wob 0.10

### ISSUE THREAD

**Issue by stx233** [francma/wob#58]
Hi I am using wob under arch linux. Wob is version 0.10. 

When typing for instance : 
$ tail -f ~/.config/wob/testwob | wob --border-color FF1793D1

**Output is :** 
1605374475.959878 ERROR main.c:571: Border color must be a value between #00000000 and #FFFFFFFF.

with an hash on the aarrggbb color : 

$ tail -f ~/.config/wob/testwob | wob --border-color #FF1793D1

**Output is :** 
wob: option '--border-color' requires an argument
Usage: wob [options]

  -h, --help                 Show help message and quit.
  --version                  Show the version number and quit.
  -v                         Increase verbosity of messages, defaults to errors and warnings only
  -t, --timeout <ms>         Hide wob after <ms> milliseconds, defaults to WOB_DEFAULT_TIMEOUT.
  -m, --max <%>              Define the maximum percentage, defaults to WOB_DEFAULT_MAXIMUM. 
  -W, --width <px>           Define bar width in pixels, defaults to WOB_DEFAULT_WIDTH. 
  -H, --height <px>          Define bar height in pixels, defaults to WOB_DEFAULT_HEIGHT. 
  -o, --offset <px>          Define border offset in pixels, defaults to WOB_DEFAULT_BORDER_OFFSET. 
  -b, --border <px>          Define border size in pixels, defaults to WOB_DEFAULT_BORDER_SIZE. 
  -p, --padding <px>         Define bar padding in pixels, defaults to WOB_DEFAULT_BAR_PADDING. 
  -a, --anchor <s>           Define anchor point; one of 'top', 'left', 'right', 'bottom', 'center' (default). 
                             May be specified multiple times. 
  -M, --margin <px>          Define anchor margin in pixels, defaults to WOB_DEFAULT_MARGIN. 
  -O, --output <name>        Define output to show bar on or '*' for all. If ommited, focused output is chosen.
                             May be specified multiple times.
  --border-color <#argb>     Define border color
  --background-color <#argb> Define background color
  --bar-color <#argb>        Define bar color

I have also tested with FFFFFFFF and #FFFFFFFF same problem 

Could you please check ?

**Comment by francma** [comment]
You need to escape `#` since it's also starting char of a comment in most shells. Like this:

```
$ tail -f ~/.config/wob/testwob | wob --border-color '#FF1793D1'
```

**Comment by stx233** [comment]
> You need to escape `#` since it's also starting char of a comment in most shells. Like this:
> 
> ```
> $ tail -f ~/.config/wob/testwob | wob --border-color '#FF1793D1'
> ```

Hi @francma 
thank you ;)
