### ISSUE TITLE
Option `--output \*` doesn't display on all displays when multiple monitors are connected (Sway)

### ISSUE THREAD

**Issue by henrywintif** [francma/wob#68]
In my Sway config, I run a script that includes the line `tail -f /tmp/wobpipe | wob -O \* &`

When I output to `/tmp/wobpipe` nothing is displayed on my two main monitors. For reference, I'm using a laptop with two external displays connected. The laptop display is disabled.

I have confirmed that the pipe does exist and is being written to.

I have fixed the issue by adding a `sleep 1` to the beginning of my script. I believe that the issue might have something to do with the displays not being initialized when Sway first starts, and that's why sleeping for one second before starting `wob` fixes the issue.

**Comment by francma** [comment]
I have recently committed this https://github.com/francma/wob/commit/17578b6cc8006224f9d9d658d3cc5a8be825faa5 which should improve the handling of connected outputs.

If the problem still persists, please attach the output of `wob -vvv` (verbose).
