### ISSUE TITLE
Wob crashes if volume is highter than 100

### ISSUE THREAD

**Issue by Zeioth** [francma/wob#85]
If the volume is higher than 100, wob should keep showing 100% instead of crashing. 

This can happen because unlike pulse/alsa, pipewire allows to increase volume without limit (even 10000%).

The -m argument doesn't help in this case.

**Comment by francma** [comment]
What command line arguments are you running wob with? What is the output when it crashes? What version are you running?

**Comment by Zeioth** [comment]
It was the stable version distributed with manjaro-sway (the one in the official arch repos, I'd say). I updated to wob-git and it's been fixed.
