### ISSUE TITLE
socket running, but doesn't work

### ISSUE THREAD

**Issue by phoneticallySAARTHaK** [francma/wob#86]
Heya, I just installed wob and set and editted the config file, copied the files into `.config/systemd/user/` as the location given in repo said 

```
systemctl --user list-units | grep wob
  wob.socket                                                                                    loaded active listening wob.socket
```
But it's not working, How do I check what's the error?

**Comment by francma** [comment]
What is the log output of wob.{socket,service}?

My guess is that you have this in your config file:

```
exec mkfifo $WOBSOCK && tail -f $WOBSOCK | wob
```

And that shouldn't be there if you are using systemd service.

**Comment by phoneticallySAARTHaK** [comment]
Yeah.. I had that the both the commands in that snippet, and the one for systemd as well, in my sway config.
Removed both the lines, and kept only the systemd one. but still not running.

How do I get the logs though?
There are no logs...
Other than listening and closing.

```
$ journalctl --user | grep wob
Dec 11 19:23:10 elixir systemd[454]: Closed wob.socket.
Dec 11 19:23:18 elixir systemd[471]: Listening on wob.socket.
Dec 11 19:23:49 elixir systemd-coredump[1145]: Process 1143 (wob) of user 1000 dumped core.
                                               Found module wob with build-id: 68c94bc14888563451ca30def0e504961389447e
                                               #8  0x000055b666593bce n/a (wob + 0x4bce)
Dec 11 19:24:38 elixir systemd-coredump[1270]: Process 1268 (wob) of user 1000 dumped core.
                                               Found module wob with build-id: 68c94bc14888563451ca30def0e504961389447e
                                               #8  0x000056032d80dbce n/a (wob + 0x4bce)
Dec 11 19:26:13 elixir systemd-coredump[1533]: Process 1531 (wob) of user 1000 dumped core.
                                               Found module wob with build-id: 68c94bc14888563451ca30def0e504961389447e
                                               #8  0x000055ac816f9bce n/a (wob + 0x4bce)
Dec 11 19:27:16 elixir systemd[471]: Closed wob.socket.
Dec 11 19:27:24 elixir systemd[463]: Listening on wob.socket.
```
I don't know about the lines around 19:23

**Comment by francma** [comment]
What if you run wob just directly from terminal?

```
Process 1268 (wob) of user 1000 dumped core
```

This indicated that wob crashes. What version of wob are you running? On what distro and compositor?

**Comment by phoneticallySAARTHaK** [comment]
wob works fine from terminal. and yes those crashes were caused by me while manually using it on terminal.
Oh and my bad. I installed wob from the git repo few days ago on fresh arch install, with sway.

**Comment by francma** [comment]
What is the output of?

```
systemctl status --user wob.*
```

**Comment by phoneticallySAARTHaK** [comment]
It is active
http://ix.io/3HHE

**Comment by francma** [comment]
It should look something like this:

```
> systemctl status --user wob.*
● wob.socket
     Loaded: loaded (/home/francma/.local/share/systemd/user/wob.socket; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-12-10 16:05:42 CET; 23h ago
   Triggers: ● wob.service
     Listen: /run/user/1000/wob.sock (FIFO)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/wob.socket

Dec 10 16:05:42 nuc systemd[950]: Listening on wob.socket.

● wob.service - A lightweight overlay volume/backlight/progress/anything bar for Wayland
     Loaded: loaded (/home/francma/.local/share/systemd/user/wob.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-12-10 16:14:31 CET; 23h ago
TriggeredBy: ● wob.socket
       Docs: man:wob(1)
   Main PID: 2341 (wob)
      Tasks: 1 (limit: 19020)
     Memory: 388.0K
        CPU: 14ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/wob.service
             └─2341 /usr/bin/wob

Dec 10 16:14:31 nuc systemd[950]: Started A lightweight overlay volume/backlight/progress/anything bar for Wayland.
```

The importat part is `TriggeredBy: ● wob.socket`. 

Does something happen if you run this?

```
echo 10 > /run/user/1000/wob.sock 
```

**Comment by phoneticallySAARTHaK** [comment]
Yup, the bar does show up
but wob.service is not running

**Comment by francma** [comment]
Does the command to modify volume/brightness from your sway config work if you run it directly in terminal?

**Comment by phoneticallySAARTHaK** [comment]
Yes it does, i use brightnessctl, and it keybinding for it works as well.
I enabled and disabled wob.service, and it did show up that it can still be enabled by wob.socket.

**Comment by francma** [comment]
Maybe the wob previously started by `exec mkfifo...` from sway config is still running? Try to kill it with `killall wob` or just do a restart.

**Comment by phoneticallySAARTHaK** [comment]
Nope, it returns no process found.
It might be an issue in my systemd config file (since I don't fully understand systemd yet) but pipewire runs fine. So i can't pinpoint the issue here

**Comment by francma** [comment]
I followed the directions in README in new Archlinux install and was able to make wob with systemd work. You can look at my dotfiles here: https://github.com/francma/dotfiles

I'm gonna close this now. Feel free to comment if you manage to get it working, Maybe the directions can be then improved to be more clear - for non-systemd people.
