### ISSUE TITLE
Feature request: use environment variables for colors

### ISSUE THREAD

**Issue by bolbishvili** [francma/wob#89]
We're using this on [sxmo](https://sxmo.org) for volume and brightness. It would be nice to be able to let the user theme wob with environment variables, for example WOB_BORDER, WOB_BACKGROUND, WOB_COLOR...

**Comment by bolbishvili** [comment]
actually, somebody pointed out this issue to me: https://github.com/francma/wob/issues/66 which would be a great solution.

**Comment by francma** [comment]
Closing in favor of https://github.com/francma/wob/issues/66
