### ISSUE TITLE
Reloading sway config file does not change aspect of bar

### ISSUE THREAD

**Issue by joaonunatingscode** [francma/wob#92]
Previously I had configured wob with default settings (just like in the sway example in [README](https://github.com/francma/wob/blob/master/README.md#sway-wm-example))

However when I changed this line
`exec mkfifo $WOBSOCK && tail -f $WOBSOCK | wob`
to
`exec mkfifo $WOBSOCK && tail -f $WOBSOCK | wob -a top`
reloaded sway, no changes were made.

**Comment by francma** [comment]
That's because `exec` is executed only when sway starts.

`exec_always` is executed on start and also on reload, but you need to kill and start wob again. Something like this:

```
exec_always killall wob; mkfifo $WOBSOCK && tail -f $WOBSOCK | wob -a top
```

This is not really a wob issue, this is how the sway and i3wm works.

**Comment by joaonunatingscode** [comment]
oh I didn't knew this, thank you

**Comment by octaskin** [comment]
Might be better to include `-g` flag on `killall` command 
```sh
exec_always killall -g wob && rm -f $WOBSOCK && mkfifo $WOBSOCK && tail -f $WOBSOCK | wob
```
This would terminate the otherwise dangling `tail` process as well.
